name: appimage-to-deb22.04

on: workflow_dispatch

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  # This yml is copied from https://github.com/hn-88/OCVWarp/blob/master/.github/workflows/cmake-nix.yml
  # and modified.
  OPENSPACE_VERSION: "0.21.0"
  APPIMAGE_VERSION: "1"
  
jobs:
  AppImageToDeb:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-22.04

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3 dpkg-dev fakeroot libfuse2




https://github.com/hn-88/OpenSpace-AppImage/releases/download/v0.21.0-1/OpenSpace-0.21.0-wayland-workaround-1-x86_64.AppImage
