name: Build OpenSpace using GHCR 24.04 Image

on:
  workflow_dispatch:

jobs:
  build-openspace:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/hn-88/ubuntu24.04-openspacebuilder-image:latest
      options: --user root  # Ensure permissions for writing to the workspace

    steps:
      - name: Clone OpenSpace repository
        run: |
          git clone --recursive https://github.com/hn-88/OpenSpace
          git checkout DebwithCPack --recurse-submodules

      - name: Create build directory
        run: |
          mkdir -p OpenSpace/build
          cd OpenSpace/build
          pwd

      - name: Configure CMake
        working-directory: OpenSpace/build
        run: |
          cmake -DCMAKE_BUILD_TYPE="Release" \
                -DCMAKE_CXX_COMPILER=/usr/bin/g++-13 \
                -DCMAKE_C_COMPILER=/usr/bin/gcc-13 \
                -DCMAKE_CXX_STANDARD=20 \
                -DASSIMP_BUILD_MINIZIP=1 \
                -DBUILD_TESTS=OFF \
                -DOPENSPACE_HAVE_TESTS=OFF \
                -DSGCT_BUILD_TESTS=OFF \
                ..

      - name: Build OpenSpace
        working-directory: OpenSpace/build
        run: |
          echo "Use the system's libvulkan, not the vendored one, otherwise they might conflict..."
          cef_orig_dir=$(find ../build -path */Release/libcef.so | xargs dirname)
          rm -v $cef_orig_dir/libvulkan.so.1
          make -j$(nproc)

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Tag image for GHCR
        run: |
          docker tag <image_name> ghcr.io/${{ github.repository_owner }}/ubuntu24.04-openspacedebbuilder-image:latest
  
      - name: Push image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/ubuntu24.04-openspacedebbuilder-image:latest


      
