name: Extract tar Artifact and List Files

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  extract-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact ZIP from another workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eu
          curl -L \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -o artifact.zip \
            "https://api.github.com/repos/hn-88/OpenSpace-AppImage/actions/artifacts/3700406409/zip"
          ls -lh artifact.zip

      - name: Unzip artifact
        run: |
          set -eu
          rm -rf artifact_unzip || true
          mkdir artifact_unzip
          unzip -q artifact.zip -d artifact_unzip
          echo "Contents of artifact_unzip:"
          find artifact_unzip -maxdepth 2 -type f -print

      - name: Detect archive type and extract
        run: |
          set -eu
          ARCHIVE_FILE=$(find artifact_unzip -type f | head -n 1 || true)
          if [ -z "$ARCHIVE_FILE" ]; then
            echo "ERROR: No file found inside artifact zip"
            exit 2
          fi
          echo "Found archive: $ARCHIVE_FILE"
          mkdir extracted
          case "$ARCHIVE_FILE" in
            *.tar)
              tar -xf "$ARCHIVE_FILE" -C extracted
              ;;
            *.tar.gz|*.tgz)
              tar -xzf "$ARCHIVE_FILE" -C extracted
              ;;
            *)
              echo "ERROR: Unsupported archive type: $ARCHIVE_FILE"
              exit 3
              ;;
          esac

      - name: Create file list
        run: |
          set -eu
          find "$(pwd)/extracted" -type f | sort > file_list.txt
          echo "File list written to file_list.txt"
          echo "Number of files: $(wc -l < file_list.txt)"

      - name: Upload file list as artifact
        uses: actions/upload-artifact@v4
        with:
          name: extracted_file_list
          path: file_list.txt
