name: Get File List from Deb Artifact

on:
  workflow_dispatch:

jobs:
  get-file-list:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download the deb artifact
      - name: Download Deb artifact ZIP (authenticated, correct headers)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -o deb_artifact.zip \
            https://api.github.com/repos/hn-88/OpenSpace-AppImage/actions/artifacts/3795253955/zip
            # https://github.com/hn-88/OpenSpace-AppImage/actions/runs/17059897978/artifacts/3795253955

      # Step 2: Unzip artifact (contains DEB file)
      - name: Unzip DEB artifact
        run: |
          mkdir deb_zip
          unzip deb_artifact.zip -d deb_zip

      # Step 3: List all files in deb
      - name: Extract file list from .deb
        run: |
          mkdir deb_extract
          dpkg-deb -x deb_zip/*.deb deb_extract
          find "$(pwd)/deb_extract" -type f | sort > deb_file_list.txt

      # Step 4: Upload deb file list
      - name: Upload deb file list
        uses: actions/upload-artifact@v4
        with:
          name: deb_file_list
          path: deb_file_list.txt

      
