name: Install and run Deb Artifact

on:
  workflow_dispatch:

jobs:
  get-file-list:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Download the deb artifact
      - name: Download Deb artifact ZIP (authenticated, correct headers)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -o deb_artifact.zip \
            https://api.github.com/repos/hn-88/OpenSpace-AppImage/actions/artifacts/3861382389/zip
            # https://github.com/hn-88/OpenSpace-AppImage/actions/runs/17257584079/artifacts/3860344645

      # Step 2: Unzip artifact (contains DEB file)
      - name: Unzip DEB artifact
        run: |
          mkdir deb_zip
          unzip deb_artifact.zip -d deb_zip

      # Step 3: List all deps and install
      - name: Extract dep list from .deb and install
        run: |
          mkdir deb_extract
          apt show ./deb_zip/*.deb > depends_file_list.txt
          sudo apt update
          sudo apt install ./deb_zip/*.deb
          
      # Step 4: run the executable
      - name: run openspace
        run: openspace
           

      
