name: Build and Push OpenSpace Builder Image to GHCR

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write  # Needed to push to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Dockerfile
        run: |
          cat <<EOF > Dockerfile
          FROM ubuntu:22.04
          ENV DEBIAN_FRONTEND=noninteractive
          RUN apt-get update && \
              apt-get install -y \
                software-properties-common && \
              add-apt-repository ppa:ubuntu-toolchain-r/test -y && \
              apt-get update && \
              apt-get install -y \
                build-essential \
                cmake \
                glew-utils \
                libpng-dev \
                freeglut3-dev \
                git \
                libxrandr-dev \
                libxinerama-dev \
                xorg-dev \
                libxcursor-dev \
                libcurl4-openssl-dev \
                libxi-dev \
                libasound2-dev \
                libgdal-dev \
                libboost1.74-dev \
                qt6-base-dev \
                libmpv-dev \
                libvulkan-dev \
                gcc-13 \
                g++-13 \
                libasound2 \
                libasound2-data \
                libasound2-plugins && \
              apt-get clean && \
              rm -rf /var/lib/apt/lists/*
          CMD ["/bin/bash"]
          EOF

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/hn-88/ubuntu22.04-openspacebuilder-image:latest .

      - name: Push image to GHCR
        run: |
          docker push ghcr.io/hn-88/ubuntu22.04-openspacebuilder-image:latest
