name: Test OpenSpace Deb Package

on:
  workflow_dispatch:

jobs:
  test-deb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # 1. Download artifact from another workflow run
      - name: Download Deb artifact ZIP (authenticated, correct headers)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -o deb_artifact.zip \
            https://api.github.com/repos/hn-88/OpenSpace-AppImage/actions/artifacts/3816066117/zip
            # https://github.com/hn-88/OpenSpace-AppImage/actions/runs/17093475969/artifacts/3807173743

      - name: Unzip DEB artifact
        run: unzip deb_artifact.zip

      # Find the .deb file in case the artifact contains multiple files
      - name: Locate DEB file
        id: find_deb
        run: |
          DEB_FILE=$(find . -name "*.deb" | head -n 1)
          echo "DEB_FILE=$DEB_FILE" >> $GITHUB_ENV
          echo "Found deb: $DEB_FILE"

      # 2. Test in clean Docker container
      - name: Test install inside minimal Ubuntu container
        run: |
          docker run --rm -v "$PWD:/workspace" ubuntu:24.04 bash -c "
            set -e
            apt-get update
            apt-get install -y curl unzip lsb-release
            echo 'Attempting to install package: $DEB_FILE'
            apt-get install -y /workspace/$DEB_FILE || true
            echo 'If apt-get failed, dependencies are missing.'
            /usr/bin/openspace --help || echo 'openspace not runnable inside container (expected if GUI needed)'
          "

      # 3. Run lintian static analysis
      - name: Install lintian
        run: sudo apt-get update && sudo apt-get install -y lintian

      - name: Run lintian checks
        run: |
          echo "Running lintian on $DEB_FILE"
          lintian "$DEB_FILE" || true

      # 4. Compare Depends vs ldd output
      - name: Inspect package metadata and binary deps
        run: |
          echo "=== Control file Depends from deb ==="
          dpkg-deb -I "$DEB_FILE" | grep Depends || true
          echo
          echo "=== Shared library dependencies (ldd) ==="
          TMPDIR=$(mktemp -d)
          dpkg-deb -x "$DEB_FILE" "$TMPDIR"
          BIN=$(find "$TMPDIR" -type f -executable -name OpenSpace | head -n 1)
          if [ -n "$BIN" ]; then
            echo "Checking binary: $BIN"
            ldd "$BIN" || true
          else
            echo "OpenSpace binary not found in package"
          fi
