name: test-feature-vckpg-branch-on-24.04

on: 
  workflow_dispatch:      # allows manual trigger
  

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  # This yml is copied from https://github.com/hn-88/OCVWarp/blob/master/.github/workflows/cmake-nix.yml
  # and modified.
  BUILD_TYPE: Release
  OPENSPACE_VERSION: "0.22.0+"
  # COMMIT_HASH: "0bec798cb39c2765373283a21312478d3d2e3c7f"
  COMMIT_HASH: "feature/vcpkg"
  
jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v6

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: true
        
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
        
    - name: Install Qt 6.9
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.9.*

    - name: Export Qt environment variables
      shell: bash
      run: |
        echo "Qt installation is at: $QT_ROOT_DIR"
    
        # For CMake find_package(Qt6 ...)
        echo "CMAKE_PREFIX_PATH=$QT_ROOT_DIR" >> $GITHUB_ENV
    
        # Common variables used by packaging scripts
        echo "Qt6_DIR=$QT_ROOT_DIR/lib/cmake/Qt6" >> $GITHUB_ENV
        echo "QT_DIR=$QT_ROOT_DIR" >> $GITHUB_ENV
    
        # Optional: add Qt tools to PATH
        echo "$QT_ROOT_DIR/bin" >> $GITHUB_PATH

        # Verify libicu* are under QT_ROOT_DIR
        find $QT_ROOT_DIR -name "libicu*"

    - name: Install CMake 4.3.2
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: '4.3.2'
    
    - name: get openspace code for a particular release
      # https://docs.openspaceproject.com/releases-v0.20/contribute/development/compiling/ubuntu.html
      run: |
        openSpaceHome="$HOME/source/OpenSpace"
        git clone --recursive https://github.com/OpenSpace/OpenSpace "$openSpaceHome"
        cd "$openSpaceHome"
        git checkout "${COMMIT_HASH}" --recurse-submodules
        # try the latest main branch, one of the latest commits
        mkdir build
        cd build

    
    - name: Install dependencies
      # https://docs.openspaceproject.com/releases-v0.20/contribute/development/compiling/ubuntu.html
      run: |
        sudo apt update
        sudo apt-get -y install glew-utils libpng-dev freeglut3-dev git libxrandr-dev libxinerama-dev xorg-dev libxcursor-dev libcurl4-openssl-dev libxi-dev libasound2-dev libgdal-dev libboost-all-dev libmpv-dev libvulkan-dev
        sudo apt-get -y install software-properties-common
        sudo apt-get -y install libasound2t64 
        # libasound2-data libasound2-plugins

    - name: Bootstrap vcpkg
      # https://github.com/OpenSpace/docker/blob/master/build/ubuntu-2604-gcc15.Dockerfile
      # private url for my reference - https://claude.ai/chat/f9d7a683-5389-44b2-a765-9926d2fa7291
      run: | 
        # define these triplets in env if using uses: lukka/run-vcpkg@v11 
        #- os: ubuntu-latest
        #  triplet: x64-linux
        #- os: ubuntu-24.04-arm     # GitHub-hosted arm64 runner
        #  triplet: arm64-linux
        #- os: macos-latest
        #  triplet: arm64-osx
        #- os: windows-latest
        #  triplet: x64-windows
        git clone https://github.com/microsoft/vcpkg "$RUNNER_TEMP/vcpkg"
        "$RUNNER_TEMP/vcpkg/bootstrap-vcpkg.sh" -disableMetrics
        echo "VCPKG_ROOT=$RUNNER_TEMP/vcpkg" >> "$GITHUB_ENV"
        echo "$RUNNER_TEMP/vcpkg" >> "$GITHUB_PATH"
        echo "VCPKG_DEFAULT_TRIPLET=x64-linux" >> "$GITHUB_ENV"
    
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        openSpaceHome="$HOME/source/OpenSpace"
        cd "$openSpaceHome/build"
        echo "Please note the extra variables passed for making the deb package ..."
        cmake -DCMAKE_TOOLCHAIN_FILE="$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_CXX_COMPILER=/usr/bin/g++-13 -DCMAKE_C_COMPILER=/usr/bin/gcc-13 \
          -DCMAKE_CXX_STANDARD=23 -DASSIMP_BUILD_MINIZIP=1 -DBUILD_TESTS=OFF -DOPENSPACE_HAVE_TESTS=OFF -DSGCT_BUILD_TESTS=OFF \
          -DOPENSPACE_DISTRO=ubuntu24.04 -DCMAKE_INSTALL_PREFIX=/usr "$openSpaceHome"

    - name: Build
      # Build your program with the given configuration
      run: |
        openSpaceHome="$HOME/source/OpenSpace"
        cd "$openSpaceHome/build"
        # Use the system's libvulkan, not the vendored one, otherwise they might conflict
        cef_orig_dir=$(find $HOME/source/OpenSpace/build -path */Release/libcef.so | xargs dirname)
        rm -vf "$cef_orig_dir/libvulkan.so.1" || echo "libvulkan.so.1 not found, skipping removal"
        cmake --build . --parallel 3
        
    
