name: test OpenSpace Docker Build

on:
  workflow_dispatch:
  

jobs:
  build-openspace:
    runs-on: ubuntu-latest

    steps:

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: false
    
      - name: Checkout OpenSpace/docker repo (for Dockerfile + build.sh)
        uses: actions/checkout@v4
        with:
          repository: hn-88/openspace-docker
          ref: 'build-OS-on-24.04-docker'
          path: docker-scripts

      - name: Build Docker image
        run: |
          docker build --no-cache \
            -f docker-scripts/build/ubuntu-2404-gcc13.Dockerfile \
            -t openspace-build \
            docker-scripts/build

      - name: Run build inside container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/OpenSpacemount \
            openspace-build \
            which cmake && which cpack && cmake --version && cpack --version && dpkg -L cmake | grep CPack.cmake && ls -ld /usr/share/cmake-* && /build.sh

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openspace-build
          path: |
            bin/
            build/*.deb
            *.deb

            
